server:
  port: 8083

mysql-options: '?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb${mysql-options}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testdb
    password: testdb
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none

security:
  oauth2:
    resource:
      filter-order: 3
