server:
  port: 8083
  context-path: /authserver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: testdb
    password: testdb
  jpa:
    hibernate:
      ddl-auto: update

security:
  oauth2:
    resource:
      filter-order: 3


